cmake_minimum_required(VERSION 4.4.1)
project(Welfs_KV_Engine)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(xxHash CONFIG REQUIRED)
add_executable(KVEngine src/main.cpp)
target_include_directories(KVEngine PRIVATE include)
target_link_libraries(KVEngine PRIVATE xxHash::xxhash)